### ISSUE TITLE
create a suitable format for the read files

### ISSUE THREAD

**Issue by raeef96** [raeef96/SofFund_group18#5]
define the structure of the input files and create one input file.

**Comment by raeef96** [comment]
define the structure of the read files so its easy to read the different values of the global variables from the input files

**Comment by andrefred** [comment]
Make it so that main() reads input from (one or more) input files, and updates the corresponding global variables based on this input.

**Comment by Gustaf-Larsson** [comment]
Decided to take the input directly in the program and not from separate files.
